UniversityMvcApp/UniversityMvcApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using UniversityMvcApp.BLL;
using UniversityMvcApp.DAL.Gateway;
using UniversityMvcApp.Models;

namespace UniversityMvcApp.Controllers
{
    
    public class CourseController : Controller
    {
        DepartmentGateway aDepartmentGateway = new DepartmentGateway();
      
        CourseManager courseManager=new CourseManager();
        private UniversityDbContext db = new UniversityDbContext();

        // GET: /Course/
        // GET: /Course/Create
        public ActionResult Create()
        {
            //ViewBag.Departments =  aDepartmentGateway.GetAllDepartment().Where( x=>x.ID<1000).Select(x=> new SelectListItem{Text = x.Name,Value = x.ID.ToString()});
            
            ViewBag.DepartmentId= new SelectList(db.Departments,"ID","Code");
            ViewBag.SemesterID = new SelectList(db.Semesters,"ID","SemesterNumber");
            return View();
        }

      

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Course course)
        {
            //ViewBag.Departments = aDepartmentGateway.GetAllDepartment().Where(x => x.ID < 100).Select(x => new SelectListItem { Text = x.Name, Value = x.ID.ToString() });
            ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            ViewBag.SemesterID = new SelectList(db.Semesters, "ID", "SemesterNumber");
            if (!courseManager.IsCodeExist(course.Code))
            {
                if (!courseManager.IsNameExist(course.Name))
                {
                    if (ModelState.IsValid)
                    {
                        db.Courses.Add(course);
                        db.SaveChanges();
                        @ViewBag.saveMessage = "Course Saved!";

                    }
                    
                    return View(course);

                }
                else
                {
                    @ViewBag.ExistMessage = "Course name already exists!";
                     return View();
                }
            }
            else
            {
                @ViewBag.ExistMessage = " Course code already exists!!";
                 return View();
            }
        }

        // GET: /Course/Edit/5

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }      
    }
}

UniversityMvcApp/UniversityMvcApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityMvcApp.BLL;
using UniversityMvcApp.Models;

namespace UniversityMvcApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        private UniversityDbContext db = new UniversityDbContext();

        // GET: /DepartmentId/
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }

        // GET: /DepartmentId/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: /DepartmentId/Create
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {


            if (!aDepartmentManager.IsCodeExist(department.Code))
            {
                if (!aDepartmentManager.IsNameExist(department.Name))
                {
                    if (ModelState.IsValid)
                    {
                        db.Departments.Add(department);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View();
                }
                else
                {
                    @ViewBag.ExistMessage = "Department name already exists!";
                    return View();
                }
            }
            else
            {
                @ViewBag.ExistMessage = "Department code already exists!";
                return View();
            }
        }

       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityMvcApp/UniversityMvcApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityMvcApp.BLL;
using UniversityMvcApp.Models;

namespace UniversityMvcApp.Controllers
{
    public class StudentController : Controller
    {
        StudentManager studentManager = new StudentManager();
        private UniversityDbContext db = new UniversityDbContext();

        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Student student = db.Students.Find(id);
           var departments = db.Departments.ToList();
           Department Department = departments.Find(a=>a.ID==student.DepartmentId);
           student.Department.Name = Department.Name;
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }
         public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Student student)
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            student.RegistrationSerial = studentManager.GetRegistration(student);
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Details", new { id=student.Id });
            }
            ViewBag.Message = "Saved successfully";
            return View(student);
        }

      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityMvcApp/UniversityMvcApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityMvcApp.BLL;
using UniversityMvcApp.Models;

namespace UniversityMvcApp.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        private UniversityDbContext db = new UniversityDbContext();

        // GET: /Teacher/
        public ActionResult Index()
        {
            return View(db.Teachers.ToList());
        }

        // GET: /Teacher/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // GET: /Teacher/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            ViewBag.DesignationId = new SelectList(db.Designations, "ID", "DesignationName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Teacher teacher)
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            ViewBag.DesignationId = new SelectList(db.Designations, "ID", "DesignationName");
            if (!aTeacherManager.DoesEmailExist(teacher.Email))
            {
                if (ModelState.IsValid)
                {
                    db.Teachers.Add(teacher);
                    db.SaveChanges();
                    ViewBag.saveMessage = "Teacher Information Saved!";
                  
                }

                return View();
            }

            else
            {
                @ViewBag.ExistMessage = "Email already exists!";
                return View();
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityMvcApp/UniversityMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Department<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Department", "Create", "Department")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Course", "Create", "Course")</li>
                            <li>@Html.ActionLink("Course Assign To Teacher", "AssignCourse", "TeacherCourseAssign")</li>  
                            <li>@Html.ActionLink("View Course Statics", "Index", "ViewCourseStatics")</li>
                            <li>@Html.ActionLink("View Class Schedule", "ViewCourseDetails", "ViewClassScheduleWithRoomAllocation")</li>
                            <li>@Html.ActionLink(" Unassign All Courses", "Index", "UnassignAllCourses")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teacher<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Teacher", "Create", "Teacher")</li>
                           
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student ", "Create", "Student")</li> 
                            <li>@Html.ActionLink("Enroll In a Course", "Add", "EnrollCourses")</li>
                            <li>@Html.ActionLink("Save Students Result", "Save", "StudentResultSave")</li>
                            <li>@Html.ActionLink("View Students Result", "ResultView", "ViewResult")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">ClassRoom<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate Classrooms", "Create", "AllocateClassRooms")</li> 
                            <li>@Html.ActionLink("Unallocate All Classroom", "Index", "UnallocateAllClassroom")</li>
                        </ul>
                    </li>

                    </ul>
                  
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Created By Null Void</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>