UniversityMvcApp/UniversityMvcApp/Models/AllocateClassRoom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityMvcApp.Models
{
    public class AllocateClassRoom
    {
        public int Id { get; set; }

        public int DepartmentId { get; set; }
        public Department Department { get; set; }

        public int CourseId { get; set; }
        public Course Course { get; set; }

        public int RoomId { get; set; }
        public Room Room { get; set; }

        public string Day { get; set; }

        public string From { get; set; }

        public string TO { get; set; }
        public TimeSpan StartTime { get; set; }

        public TimeSpan FinishTime { get; set; }

    }
}

UniversityMvcApp/UniversityMvcApp/Controllers/AllocateClassRoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityMvcApp.BLL;
using UniversityMvcApp.Models;

namespace UniversityMvcApp.Controllers
{
    public class AllocateClassRoomsController : Controller
    {
        private UniversityDbContext db = new UniversityDbContext();

        AllocateClassRoomManager allocateClassroomManager = new AllocateClassRoomManager();

        // GET: AllocateClassRooms
        public ActionResult Index()
        {
            var allocateClassRooms = db.AllocateClassRooms.Include(a => a.Course).Include(a => a.Department).Include(a => a.Room);
            return View(allocateClassRooms.ToList());
        }

        // GET: AllocateClassRooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AllocateClassRoom allocateClassRoom = db.AllocateClassRooms.Find(id);
            if (allocateClassRoom == null)
            {
                return HttpNotFound();
            }
            return View(allocateClassRoom);
        }

        // GET: AllocateClassRooms/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Code");
            //ViewBag.DepartmentId = new SelectList(db.Departments, "ID", "Code");
            ViewBag.DepartmentId = db.Departments.ToList();

            ViewBag.RoomId = new SelectList(db.Rooms, "Id", "RoomNo");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(AllocateClassRoom allocateClassRoom)
        {
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Code", allocateClassRoom.CourseId);
            ViewBag.DepartmentId = db.Departments.ToList();
            ViewBag.RoomId = new SelectList(db.Rooms, "Id", "RoomNo", allocateClassRoom.RoomId);
            allocateClassRoom.StartTime = DateTime.ParseExact(allocateClassRoom.From, "h:mm tt", CultureInfo.InvariantCulture).TimeOfDay;
            allocateClassRoom.FinishTime = DateTime.ParseExact(allocateClassRoom.TO, "h:mm tt", CultureInfo.InvariantCulture).TimeOfDay;
            if (!AllocateClassRoomManager.HasClass(allocateClassRoom))
            {
                if (allocateClassroomManager.IsTimeAlocated(allocateClassRoom))
                {
                    ViewBag.Errormessage = "Room Is Allocated For This Time Interval";
                    return View();
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        db.AllocateClassRooms.Add(allocateClassRoom);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                        ViewBag.saveMessage = "Allocated Succesfully!!!";
                    }


                    return View(allocateClassRoom);

                }
            }
            else
            {
                ViewBag.Errormessage = "This Course has already been allocated at this time";
                return View(allocateClassRoom);
            }
           
        }

        public JsonResult GetCourseByDepartmentId(int departmentId)
        {
            //List<Course> course = db.Courses.ToList();

            List<Course> course = allocateClassroomManager.GetCourseByDepartmentId();
            var courses = course.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(courses);
            //return Json(courses, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRoomsByDepartmentId(int departmentId)
        {
            List<Room> rooms = db.Rooms.ToList();
            var room = rooms.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(room);
           
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

UniversityMvcApp/UniversityMvcApp/Views/AllocateClassRooms/Create.cshtml
@using System.Web.Mvc.Html
@model UniversityMvcApp.Models.AllocateClassRoom

@{
    ViewBag.Title = "Create";
    string Errormessage = ViewBag.Errormessage;
    string allocatedMessage = ViewBag.allocatedMessage;
}
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Scripts/jonthornton-jquery-timepicker-0e3e903/jquery.timepicker.css" rel="stylesheet" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<h2>AllocateClassRoom</h2>

@if (Errormessage != null)
{
    <label>@Errormessage</label>
}
@if (allocatedMessage != null)
{
    <label>@allocatedMessage</label>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="DepartmentId" id="DepartmentId">
                    <option>--Select--</option>
                    @foreach (var department in ViewBag.DepartmentId)
                    {
                        <option value="@department.ID">@department.Code</option>
                    }
                    @*@Html.DropDownList("DepartmentId")*@

                </select>

                @Html.ValidationMessageFor(model => model.DepartmentId)

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="CourseId" id="CourseId"></select>

                @*@Html.DropDownList("CourseId")*@

                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "Room", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<select name="RoomId" id="RoomId"></select>*@
                @Html.DropDownList("RoomId","--Select--")
                @Html.ValidationMessageFor(model => model.RoomId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Day" id="Day">
                    <option value="">--Select--</option>
                    <option value="Saturday">Saturday</option>
                    <option value="Sunday">Sunday</option>
                    <option value="Monday">Monday</option>
                    <option value="Tuesday">Tuesday</option>
                    <option value="Wednesday">Wednesday</option>
                    <option value="Thrusday">Thrusday</option>
                    <option value="Friday">Friday</option>
                </select>
                @Html.ValidationMessageFor(model => model.Day)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.From, new { @class = "From" })
                @Html.ValidationMessageFor(model => model.From)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TO, new { @class = "TO" })
                @Html.ValidationMessageFor(model => model.TO)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jquery")
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

    <script type="text/javascript">
        $('.From,.TO').timepicker({
            timeFormat: 'h:mm p',
            interval: 30,
            minTime: '8',
            maxTime: '6:00pm',
            defaultTime: '8',
            startTime: '8:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });


        $(document).ready(function () {
            //var table = $("#myTable").DataTable();
            $("#DepartmentId").change(function () {
                var deptId = $("#DepartmentId").val();
                //$("#myTable").show();
                //table.clear().draw(false);
                //$("#tableBody").empty();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="">Select</option>');
                var json = { DepartmentId: deptId };
                //alert(deptId);
                $.ajax({
                    type: "POST",
                    @*//url: '@Url.Action("GetCourseByDepartmentId", "AllocateClassRooms")',*@
                    url: '/AllocateClassRooms/GetCourseByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {

                            //alert(key);
                            $("#CourseId").append('<option value="' + value.Id + '">' + value.Code + '</option>');
                            //$("#tableBody").append('<tr><td>' + value.StudentId + '</td><td>' + value.Name + '</td><td>' + value.DepartmentId + '</td></tr>');
                            //table.row.add([
                            //    value.StudentId, value.Name, value.DepartmentId
                            //]).draw(false);
                        });
                    }
                });
            });
        });

       
    </script>
}

UniversityMvcApp/UniversityMvcApp/Views/AllocateClassRooms/Delete.cshtml
@model UniversityMvcApp.Models.AllocateClassRoom

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AllocateClassRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityMvcApp/UniversityMvcApp/Views/AllocateClassRooms/Details.cshtml
@model UniversityMvcApp.Models.AllocateClassRoom

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AllocateClassRoom</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UniversityMvcApp/UniversityMvcApp/Views/AllocateClassRooms/Edit.cshtml
@model UniversityMvcApp.Models.AllocateClassRoom

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AllocateClassRoom</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", String.Empty)
                @Html.ValidationMessageFor(model => model.RoomId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Day)
                @Html.ValidationMessageFor(model => model.Day)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From)
                @Html.ValidationMessageFor(model => model.From)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TO, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TO)
                @Html.ValidationMessageFor(model => model.TO)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinishTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinishTime)
                @Html.ValidationMessageFor(model => model.FinishTime)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UniversityMvcApp/UniversityMvcApp/Views/AllocateClassRooms/Index.cshtml
@model IEnumerable<UniversityMvcApp.Models.AllocateClassRoom>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Room.RoomNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Room.RoomNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinishTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>