UniversityMvcApp/UniversityMvcApp/Controllers/TeacherCourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityMvcApp.BLL;
using UniversityMvcApp.Models;


namespace UniversityMvcApp.Controllers
{
    public class TeacherCourseAssignController : Controller
    {
        private UniversityDbContext db = new UniversityDbContext();
        DepartmentManager aDepartmentManager=new DepartmentManager();
        TeacherManager aTeacherManager= new TeacherManager();
        CourseManager aCoursemanager = new CourseManager();
        //
        // GET: /TeacherCourseAssign/
        public ActionResult AssignCourse()
        {
            ViewBag.Departments = aDepartmentManager.GetDepartments();
            return View();
        }
        [HttpPost]
        public ActionResult AssignCourse(Course Courses)
        {
            ViewBag.Departments = aDepartmentManager.GetDepartments();
            if(!aCoursemanager.IsCourseAssign(Courses.Id))
            {
                bool message = aCoursemanager.AssignTeacher(Courses);
                if (message)
                {
                    ViewBag.message="Successfully Course Assigned!";
                }
                else
                {
                     ViewBag.message="Course Assign Failed!";
                }
            }
            else
            {
                ViewBag.error="This Course Has Already Assigned To a Teacher";
            }
            return View();
        }
        public JsonResult GetTeacherByDepartmentId(int departmentId)
        {
            List<Teacher> teachers = aTeacherManager.GetTeachers();
            var teacherList = teachers.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(teacherList);
        }
        public JsonResult GetTeacherByTeacherId(int teacherId)
        {
            List<Teacher> teachers = aTeacherManager.GetTeachers();
            var teacher = teachers.Find(a => a.ID ==teacherId);
            List<Course> courses = aCoursemanager.GetAllCourses();
            var coursesofTeacher = courses.Where(a =>a.TeacherId == teacherId).ToList();
            teacher.CreditTaken = 0;
            foreach (var course in coursesofTeacher)
            {
                teacher.CreditTaken += course.Credit;
            }
            teacher.RemainingCredit = teacher.CreditToBeTaken - teacher.CreditTaken;
            return Json(teacher);
        }
        public JsonResult GetCourseByCourseId(int CourseId)
        {
          
            List<Course> courses = aCoursemanager.GetAllCourses();
            var course = courses.Find(a => a.Id == CourseId);
            return Json(course);
        }
        public JsonResult GetCourseIdByDepartmentId(int DepartmentId)
        {

            List<Course> courses = aCoursemanager.GetAllCourses();
            var course = courses.Where(a => a.DepartmentId == DepartmentId).ToList();
            return Json(course);
        }
       
       
	}
}

UniversityMvcApp/UniversityMvcApp/Views/TeacherCourseAssign/AssignCourse.cshtml
@model  UniversityMvcApp.Models.Course
@{
    ViewBag.Title = "AssignCourse";
   string message = ViewBag.message;
   string error = ViewBag.error;
}

<h2>Course Assign to Teacher</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
    @if (message!=null)
    {
      <label>@message</label>  
    }
    @if (error != null)
    {
        <label>@error</label>
    }
    <div>
        <form method="POST" id="myForm">
            <fieldset>

                <table>
                    <tr>
                        <td>
                            <label for="departmentId">DepartmentId</label>
                        </td>
                        <td>
                            <select name="departmentId" id="departmentId">
                                <option value="">Select...</option>
                                @foreach (var department in ViewBag.Departments)
                                {
                                    <option value="@department.ID">@department.Code</option>
                                }
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <td><label for="TeacherId">Teacher</label></td>
                        <td>
                            <select name="TeacherId" id="TeacherId"></select>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="CreditToBeTaken">Credit To Be Taken</label></td>
                        <td>
                            <input type="text" name="CreditToBeTaken" id="CreditToBeTaken"></input>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="RemainingCredit">Remaining Credit</label></td>
                        <td>
                            <input type="text" name="RemainingCredit" id="RemainingCredit"></input>
                        </td>
                    </tr>

                    <tr>
                        <td><label for="CourseId">Course Code</label></td>
                        <td>
                            <select name="Id" id="Id"></select>
                        </td>
                    </tr>

                    <tr>
                        <td><label for="CourseName">Name</label></td>
                        <td>
                            <input type="text" name="CourseName" id="CourseName"></input>
                        </td>
                    </tr>

                    <tr>
                        <td><label for="CourseCredit">Credit</label></td>
                        <td>
                           <input type="text" name="CourseCredit" id="CourseCredit"></input>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" id="submit" value="Assign" class="btn btn-default" /></td>
                    </tr>
                </table>
            </fieldset>
        </form>

    </div>                                @*  
      </script><script src="~/Scripts/DataTables/jquery.dataTables.js"></script>*@
    @section scripts
    {
    <script>
    $(document).ready(function
                     () {
                         //var table = $("#myTable").DataTable();
                         $("#departmentId").change(function ()
                         {
                             var deptId
                             = $("#departmentId").val();
                             //$("#myTable").show();
                             //table.clear().draw(false);
                             //$("#tableBody").empty();
                             $("#TeacherId").empty();
                                  $("#TeacherId").append('<option value="">Select</option>');
                   var json = { departmentId: deptId } ;
                                 $.ajax(
                             {
                                 type: "POST",
                                 //url: '@Url.Action("GetTeacherByDepartmentId", "TeacherCourseAssign")',
                                 url: '/TeacherCourseAssign/GetTeacherByDepartmentId',
                                 contentType: "application/json; charset=utf-8",
                                 data: JSON.stringify(json),
                                 success: function
                                 (data) {
                                     //alert(data);
                                     $.each(data,
                                     function (key,
                                     value) {
                                         //alert(key);
                                         $("#TeacherId").append('<option value="' + value.ID + '">'
                                         + value.Name
                                         + '</option>');


                                     }
                                     );
                                 }
                             }
                             );
                         }
                         );
                     }
                     );
                         $(document).ready(function
                     () {
                         //var table = $("#myTable").DataTable();
                         $("#TeacherId").change(function ()
                         {
                             var TeachId
                             = $("#TeacherId").val();
                             //$("#myTable").show();
                             //table.clear().draw(false);
                             //$("#tableBody").empty();
                      var json = { teacherId: TeachId };
                      $.ajax(
                             {
                                 type: "POST",
                                 //url: '@Url.Action("GetTeacherByDepartmentId", "TeacherCourseAssign")',
                                 url: '/TeacherCourseAssign/GetTeacherByTeacherId',
                                 contentType: "application/json; charset=utf-8",
                                 data: JSON.stringify(json),
                                 success: function
                                 (data) {
                     $("#CreditToBeTaken").val(data.CreditToBeTaken),
                      $("#RemainingCredit").val(data.RemainingCredit);
                                         //alert(key);





                                 }
                             }
                             );
                         }
                         );
                     }
                     );
                            // CourseId Drop Down


                             $(document).ready(function
                     () {
                         //var table = $("#myTable").DataTable();
                         $("#departmentId").change(function ()
                         {
                             var deptId
                             = $("#departmentId").val();
                             //$("#myTable").show();
                             //table.clear().draw(false);
                             //$("#tableBody").empty();
                             $("#Id").empty();
                                  $("#Id").append('<option value="">Select</option>');
                   var json = { departmentId: deptId } ;
                                 $.ajax(
                             {
                                 type: "POST",
                                 //url: '@Url.Action("GetTeacherByDepartmentId", "TeacherCourseAssign")',
                                 url: '/TeacherCourseAssign/GetCourseIdByDepartmentId',
                                 contentType: "application/json; charset=utf-8",
                                 data: JSON.stringify(json),
                                 success: function
                                 (data) {
                                     //alert(data);
                                     $.each(data,
                                     function (key,
                                     value) {
                                         //alert(key);
                                         $("#Id").append('<option value="' + value.Id + '">'
                                         + value.Code
                                         + '</option>');


                                     }
                                     );
                                 }
                             }
                             );
                         }
                         );
                     }
                     );


                        //courseId
                        $(document).ready(function
                     () {
                         //var table = $("#myTable").DataTable();
                         $("#Id").change(function ()
                         {
                             var CoId
                             = $("#Id").val();
                             //$("#myTable").show();
                             //table.clear().draw(false);
                             //$("#tableBody").empty();
                      var json = { CourseId: CoId };
                      $.ajax(
                             {
                                 type: "POST",
                                 //url: '@Url.Action("GetCourseByCourseId", "TeacherCourseAssign")',
                                 url: '/TeacherCourseAssign/GetCourseByCourseId',
                                 contentType: "application/json; charset=utf-8",
                                 data: JSON.stringify(json),
                                 success: function
                                 (data) {
                     $("#CourseCredit").val(data.Credit),
                      $("#CourseName").val(data.Name);
                                         //alert(key);





                                 }
                             }
                             );
                         }
                         );
                     }
                     );
                                     $(document).ready(function
                     () {
      $("#submit").click(function(){
                                 var CC=$("#CourseCredit").val();
                                          var CourseCredit=parseInt(CC);
                                    var RC=$("#RemainingCredit").val();
                                           var RemainingCredit=parseInt(RC);
                 if(CourseCredit>RemainingCredit)
                    {
                                      var r = confirm("Credit is more than teacher’s remaining credit.Do you want to Assign this course?");

                 //cancel clicked : stop button default action
                 if (r === false) {
                     return false;
                                  }

                  //action continues, saves in database, no need for more code


                      }

             });
                                    });</script>
   }
   </body>
</html>